### PR TITLE
Use posframe to preview image

### PR DESCRIPTION
**Pull request by tumashu**
See #99

### CODE REVIEW

**Comment by abo-abo** [comment]
Doesn't work correctly for me. The child frame blinks the previous image before showing the current image.

Please don't require `posframe` at top level, do it in `org-download--display-inline-images`.

Please don't use `shell-command`: it produces user-visible output. Use either `shell-command-to-string` or `process-file`.

**Comment by tumashu** [comment]
```
The child frame blinks the previous image before showing the current image.
```
Do not understand, suggest screenshot :-)

**Comment by abo-abo** [comment]
The frame displays the old image for 0.2s, then the new image, then disappears.

Also, the thumbnails are placed in the current directory. I think they should go to `/tmp/` instead.

**Comment by tumashu** [comment]
linux or macos?

**Comment by abo-abo** [comment]
Linux. Emacs 26.1.

**Comment by tumashu** [comment]
I have tested in debian unstable, emacs26,  and can not find the problem: The frame displays the old image for 0.2s, then the new image, then disappears.

**Comment by abo-abo** [comment]
Thanks, I've merged the changes. I still see the issue on my machine. But since this feature is off by default, it's OK. Let's see if someone can also reproduce it.

**Pull request closed without merging**
