### PR TITLE
use magick to accessing clipboard on windows

### PR DESCRIPTION
**Pull request by shelper**
ImageMagick no long has separate executable called convert, you need to use magick directly

### CODE REVIEW

**Comment by kholway** [comment]
This fix also solves an issue with unexpected behavior due to "convert" already existing on the windows path (`C:\WINDOWS\system32\convert.exe`).

**Review by thatboyjake — COMMENTED** [review]
sick

**Comment by Horrih** [comment]
Any news on a merge of this PR ?

I wasted some time thinking I was doing things wrong, but this pull request is right

**Comment by abo-abo** [comment]
Merged, thanks!

**Pull request closed without merging**
